import array as np
import math as pi
from pyautocad import Autocad, APoint, aDouble, math

acad = Autocad(create_if_not_exists=True)
acad.prompt("Hello, Autocad from Python\n")
print(acad.doc.Name)

class shapes():

    def draw0(self,x, y, w, h):
        import array as np
        import math as pi
        from pyautocad import Autocad, APoint, aDouble, math

        acad = Autocad(create_if_not_exists=True)
        acad.prompt("Hello, Autocad from Python\n")
        print(acad.doc.Name)

        ################
        acad.model.AddSpline(aDouble(x + 1095.9355 * w / 900, y + 1613.1246 * h / 2270, 0,
                                     x + 1117.9234 * w / 900, y + 1403.1246 * h / 2270, 0,
                                     x + 1161.1739 * w / 900, y + 1155.8378 * h / 2270, 0,
                                     x + 1228.5131 * w / 900, y + 893.1246 * h / 2270, 0,
                                     x + 1375.4413 * w / 900, y + 496.0295 * h / 2270, 0,
                                     ), APoint(0, 0), APoint(0, 0))

        ###########

        acad.model.AddPolyLine(aDouble(x + 1375.4413 * w / 900, y + 496.0295 * h / 2270, 0,
                                       x + 1375.4413 * w / 900, y + 2123.1246 * h / 2270, 0,
                                       x + 1087.0413 * w / 900, y + 2123.1246 * h / 2270, 0,
                                       x + 1095.9355 * w / 900, y + 1613.1246 * h / 2270, 0,
                                       ))

        ########
        p0 = acad.model.AddLine(APoint(x + 155.1666 * w / 900, y + 1845.5913 * h / 2270),
                                APoint(x + 405.1666 * w / 900, y + 1845.5913 * h / 2270))
        p1 = acad.model.AddLine(APoint(x + 405.1666 * w / 900, y + 1845.5913 * h / 2270),
                                APoint(x + 405.1666 * w / 900, y + 2123.9246 * h / 2270))
        p2 = acad.model.AddLine(APoint(x + 405.1666 * w / 900, y + 2123.9246 * h / 2270),
                                APoint(x + 155.1666 * w / 900, y + 2123.9246 * h / 2270))
        p3 = acad.model.AddLine(APoint(x + 155.1666 * w / 900, y + 2123.9246 * h / 2270),
                                APoint(x + 155.1666 * w / 900, y + 1845.5913 * h / 2270))
        ##### light #####
        p4 = acad.model.AddLine(APoint(x + 155.1666 * w / 900, y + 1845.5913 * h / 2270),
                                APoint(x + 160.1666 * w / 900, y + 1850.5913 * h / 2270))
        p5 = acad.model.AddLine(APoint(x + 160.1666 * w / 900, y + 1850.5913 * h / 2270),
                                APoint(x + 400.1666 * w / 900, y + 1850.5913 * h / 2270))
        p6 = acad.model.AddLine(APoint(x + 400.1666 * w / 900, y + 1850.5913 * h / 2270),
                                APoint(x + 400.1666 * w / 900, y + 2118.9246 * h / 2270))
        p7 = acad.model.AddLine(APoint(x + 400.1666 * w / 900, y + 2118.9246 * h / 2270),
                                APoint(x + 160.1666 * w / 900, y + 2118.9246 * h / 2270))
        ##### light #####
        p8 = acad.model.AddLine(APoint(x + 160.1666 * w / 900, y + 2118.9246 * h / 2270),
                                APoint(x + 160.1666 * w / 900, y + 1850.5913 * h / 2270))
        p9 = acad.model.AddLine(APoint(x + 160.1666 * w / 900, y + 1850.5913 * h / 2270),
                                APoint(x + 175.1666 * w / 900, y + 1865.5913 * h / 2270))
        p10 = acad.model.AddLine(APoint(x + 175.1666 * w / 900, y + 1865.5913 * h / 2270),
                                 APoint(x + 385.1666 * w / 900, y + 1865.5913 * h / 2270))
        p11 = acad.model.AddLine(APoint(x + 385.1666 * w / 900, y + 1865.5913 * h / 2270),
                                 APoint(x + 385.1666 * w / 900, y + 2103.9246 * h / 2270))
        ##### light #####
        p12 = acad.model.AddLine(APoint(x + 385.1666 * w / 900, y + 2103.9246 * h / 2270),
                                 APoint(x + 175.1666 * w / 900, y + 2103.9246 * h / 2270))
        p13 = acad.model.AddLine(APoint(x + 175.1666 * w / 900, y + 2103.9246 * h / 2270),
                                 APoint(x + 175.1666 * w / 900, y + 1865.5913 * h / 2270))
        p14 = acad.model.AddLine(APoint(x + 175.1666 * w / 900, y + 1865.5913 * h / 2270),
                                 APoint(x + 183.1666 * w / 900, y + 1873.5913 * h / 2270))
        p15 = acad.model.AddLine(APoint(x + 183.1666 * w / 900, y + 1873.5913 * h / 2270),
                                 APoint(x + 377.1666 * w / 900, y + 1873.5913 * h / 2270))
        ##### light #####
        p16 = acad.model.AddLine(APoint(x + 377.1666 * w / 900, y + 1873.5913 * h / 2270),
                                 APoint(x + 377.1666 * w / 900, y + 2095.9246 * h / 2270))
        p17 = acad.model.AddLine(APoint(x + 377.1666 * w / 900, y + 2095.9246 * h / 2270),
                                 APoint(x + 183.1666 * w / 900, y + 2095.9246 * h / 2270))
        p18 = acad.model.AddLine(APoint(x + 183.1666 * w / 900, y + 2095.9246 * h / 2270),
                                 APoint(x + 183.1666 * w / 900, y + 1873.5913 * h / 2270))
        p19 = acad.model.AddLine(APoint(x + 183.1666 * w / 900, y + 1873.5913 * h / 2270),
                                 APoint(x + 183.1666 * w / 900, y + 2095.9246 * h / 2270))
        ##### light #####
        p4.delete()

        p9.delete()

        p14.delete()

        p19.delete()

        p01 = acad.model.AddLine(APoint(x + 155.1666 * w / 900, y + 1507.2579 * h / 2270),
                                 APoint(x + 423.149 * w / 900, y + 1507.2579 * h / 2270))
        p11 = acad.model.AddLine(APoint(x + 423.149 * w / 900, y + 1507.2579 * h / 2270),
                                 APoint(x + 405.9048 * w / 900, y + 1785.5913 * h / 2270))
        p21 = acad.model.AddLine(APoint(x + 405.9048 * w / 900, y + 1785.5913 * h / 2270),
                                 APoint(x + 155.1666 * w / 900, y + 1785.5913 * h / 2270))
        p31 = acad.model.AddLine(APoint(x + 155.1666 * w / 900, y + 1785.5913 * h / 2270),
                                 APoint(x + 155.1666 * w / 900, y + 1507.2579 * h / 2270))
        ##### light #####
        p41 = acad.model.AddLine(APoint(x + 155.1666 * w / 900, y + 1507.2579 * h / 2270),
                                 APoint(x + 160.1666 * w / 900, y + 1512.2579 * h / 2270))
        p51 = acad.model.AddLine(APoint(x + 160.1666 * w / 900, y + 1512.2579 * h / 2270),
                                 APoint(x + 417.6118 * w / 900, y + 1512.2579 * h / 2270))
        p61 = acad.model.AddLine(APoint(x + 417.6118 * w / 900, y + 1512.2579 * h / 2270),
                                 APoint(x + 401.0127 * w / 900, y + 1780.5913 * h / 2270))
        p71 = acad.model.AddLine(APoint(x + 401.0127 * w / 900, y + 1780.5913 * h / 2270),
                                 APoint(x + 160.1666 * w / 900, y + 1780.5913 * h / 2270))
        ##### light #####
        p81 = acad.model.AddLine(APoint(x + 160.1666 * w / 900, y + 1780.5913 * h / 2270),
                                 APoint(x + 160.1666 * w / 900, y + 1512.2579 * h / 2270))
        p91 = acad.model.AddLine(APoint(x + 160.1666 * w / 900, y + 1512.2579 * h / 2270),
                                 APoint(x + 175.1666 * w / 900, y + 1527.2579 * h / 2270))
        p101 = acad.model.AddLine(APoint(x + 175.1666 * w / 900, y + 1527.2579 * h / 2270),
                                  APoint(x + 401.0543 * w / 900, y + 1527.2579 * h / 2270))
        p111 = acad.model.AddLine(APoint(x + 401.0543 * w / 900, y + 1527.2579 * h / 2270),
                                  APoint(x + 386.3779 * w / 900, y + 1765.5913 * h / 2270))
        ##### light #####
        p121 = acad.model.AddLine(APoint(x + 386.3779 * w / 900, y + 1765.5913 * h / 2270),
                                  APoint(x + 175.1666 * w / 900, y + 1765.5913 * h / 2270))
        p131 = acad.model.AddLine(APoint(x + 175.1666 * w / 900, y + 1765.5913 * h / 2270),
                                  APoint(x + 175.1666 * w / 900, y + 1527.2579 * h / 2270))
        p141 = acad.model.AddLine(APoint(x + 175.1666 * w / 900, y + 1527.2579 * h / 2270),
                                  APoint(x + 183.1666 * w / 900, y + 1535.2579 * h / 2270))
        p151 = acad.model.AddLine(APoint(x + 183.1666 * w / 900, y + 1535.2579 * h / 2270),
                                  APoint(x + 392.2562 * w / 900, y + 1535.2579 * h / 2270))
        ##### light #####
        p161 = acad.model.AddLine(APoint(x + 392.2562 * w / 900, y + 1535.2579 * h / 2270),
                                  APoint(x + 378.5981 * w / 900, y + 1757.5913 * h / 2270))
        p171 = acad.model.AddLine(APoint(x + 378.5981 * w / 900, y + 1757.5913 * h / 2270),
                                  APoint(x + 183.1666 * w / 900, y + 1757.5913 * h / 2270))
        p181 = acad.model.AddLine(APoint(x + 183.1666 * w / 900, y + 1757.5913 * h / 2270),
                                  APoint(x + 183.1666 * w / 900, y + 1535.2579 * h / 2270))
        p191 = acad.model.AddLine(APoint(x + 183.1666 * w / 900, y + 1535.2579 * h / 2270),
                                  APoint(x + 183.1666 * w / 900, y + 1757.5913 * h / 2270))
        ##### light #####
        p41.delete()

        p91.delete()

        p141.delete()

        p191.delete()

        ###########################################
        l = [x + 0 * w / 900, y + 0 * h / 2270, 0, x + 900 * w / 900, y + 0 * h / 2270, 0, x + 900 * w / 900,
             y + 2270 * h / 2270, 0, x + 0 * w / 900, y + 2270 * h / 2270, 0, x + 0 * w / 900, y + 0 * h / 2270, 0]
        l1 = [x + 150 * w / 900, y + 428.3333 * h / 2270, 0, x + 150 * w / 900, y + 150 * h / 2270, 0,
              x + 750 * w / 900, y + 150 * h / 2270, 0, x + 750 * w / 900, y + 428.3333 * h / 2270, 0,
              x + 150 * w / 900, y + 428.3333 * h / 2270, 0]
        l2 = [x + 155 * w / 900, y + 423.3333 * h / 2270, 0, x + 155 * w / 900, y + 155 * h / 2270, 0,
              x + 745 * w / 900, y + 155 * h / 2270, 0, x + 745 * w / 900, y + 423.3333 * h / 2270, 0,
              x + 155 * w / 900, y + 423.3333 * h / 2270, 0]
        l3 = [x + 170 * w / 900, y + 408.3333 * h / 2270, 0, x + 170 * w / 900, y + 170 * h / 2270, 0,
              x + 730 * w / 900, y + 170 * h / 2270, 0, x + 730 * w / 900, y + 408.3333 * h / 2270, 0,
              x + 170 * w / 900, y + 408.3333 * h / 2270, 0]
        l4 = [x + 178 * w / 900, y + 400.3333 * h / 2270, 0, x + 178 * w / 900, y + 178 * h / 2270, 0,
              x + 722 * w / 900, y + 178 * h / 2270, 0, x + 722 * w / 900, y + 400.3333 * h / 2270, 0,
              x + 178 * w / 900, y + 400.3333 * h / 2270, 0]
        l5 = [x + 150 * w / 900, y + 488.3333 * h / 2270, 0, x + 150 * w / 900, y + 766.6667 * h / 2270, 0,
              x + 577.393 * w / 900, y + 766.6667 * h / 2270, 0, x + 684.444 * w / 900, y + 488.3333 * h / 2270, 0,
              x + 150 * w / 900, y + 488.3333 * h / 2270, 0]
        l6 = [x + 155 * w / 900, y + 493.3333 * h / 2270, 0, x + 155 * w / 900, y + 761.6667 * h / 2270, 0,
              x + 573.7981 * w / 900, y + 761.6667 * h / 2270, 0, x + 676.8216 * w / 900, y + 493.3333 * h / 2270, 0,
              x + 155 * w / 900, y + 493.3333 * h / 2270, 0]
        l7 = [x + 170 * w / 900, y + 508.3333 * h / 2270, 0, x + 170 * w / 900, y + 746.6667 * h / 2270, 0,
              x + 563.037 * w / 900, y + 746.6667 * h / 2270, 0, x + 654.0647 * w / 900, y + 508.3333 * h / 2270, 0,
              x + 170 * w / 900, y + 508.3333 * h / 2270, 0]
        l8 = [x + 178 * w / 900, y + 516.3333 * h / 2270, 0, x + 178 * w / 900, y + 738.6667 * h / 2270, 0,
              x + 557.3123 * w / 900, y + 738.6667 * h / 2270, 0, x + 641.9944 * w / 900, y + 516.3333 * h / 2270, 0,
              x + 178 * w / 900, y + 516.3333 * h / 2270, 0]

        p0 = acad.model.AddPolyline(aDouble(l))
        p1 = acad.model.AddPolyline(aDouble(l1))
        p2 = acad.model.AddPolyline(aDouble(l2))
        p3 = acad.model.AddPolyline(aDouble(l3))
        p4 = acad.model.AddPolyline(aDouble(l4))
        p5 = acad.model.AddPolyline(aDouble(l5))
        p6 = acad.model.AddPolyline(aDouble(l6))
        p7 = acad.model.AddPolyline(aDouble(l7))
        p8 = acad.model.AddPolyline(aDouble(l8))

        ##################################### new test
        acad.model.AddLine(APoint(x + 150 * w / 900, y + 826.6667 * h / 2270),
                           APoint(x + 557.8869 * w / 900, y + 826.6667 * h / 2270))
        acad.model.AddLine(APoint(x + 557.8869 * w / 900, y + 826.6667 * h / 2270),
                           APoint(x + 482.9685 * w / 900, y + 1105 * h / 2270))
        acad.model.AddLine(APoint(x + 482.9685 * w / 900, y + 1105 * h / 2270),
                           APoint(x + 150 * w / 900, y + 1105 * h / 2270))
        acad.model.AddLine(APoint(x + 150 * w / 900, y + 1105 * h / 2270),
                           APoint(x + 150 * w / 900, y + 826.6667 * h / 2270))
        acad.model.AddLine(APoint(x + 150 * w / 900, y + 826.6667 * h / 2270),
                           APoint(x + 155 * w / 900, y + 831.6667 * h / 2270))
        acad.model.AddLine(APoint(x + 155 * w / 900, y + 831.6667 * h / 2270),
                           APoint(x + 551.0772 * w / 900, y + 831.6667 * h / 2270))
        acad.model.AddLine(APoint(x + 551.0772 * w / 900, y + 831.6667 * h / 2270),
                           APoint(x + 478.9686 * w / 900, y + 1100 * h / 2270))
        acad.model.AddLine(APoint(x + 478.9686 * w / 900, y + 1100 * h / 2270),
                           APoint(x + 155 * w / 900, y + 1100 * h / 2270))
        acad.model.AddLine(APoint(x + 155 * w / 900, y + 1100 * h / 2270),
                           APoint(x + 155 * w / 900, y + 831.6667 * h / 2270))
        acad.model.AddLine(APoint(x + 155 * w / 900, y + 831.6667 * h / 2270),
                           APoint(x + 170 * w / 900, y + 846.6667 * h / 2270))
        acad.model.AddLine(APoint(x + 170 * w / 900, y + 846.6667 * h / 2270),
                           APoint(x + 530.7329 * w / 900, y + 846.6667 * h / 2270))
        acad.model.AddLine(APoint(x + 530.7329 * w / 900, y + 846.6667 * h / 2270),
                           APoint(x + 466.9978 * w / 900, y + 1085 * h / 2270))
        acad.model.AddLine(APoint(x + 466.9978 * w / 900, y + 1085 * h / 2270),
                           APoint(x + 170 * w / 900, y + 1085 * h / 2270))
        acad.model.AddLine(APoint(x + 170 * w / 900, y + 1085 * h / 2270),
                           APoint(x + 170 * w / 900, y + 846.6667 * h / 2270))
        acad.model.AddLine(APoint(x + 170 * w / 900, y + 846.6667 * h / 2270),
                           APoint(x + 178 * w / 900, y + 854.6667 * h / 2270))
        acad.model.AddLine(APoint(x + 178 * w / 900, y + 854.6667 * h / 2270),
                           APoint(x + 519.9339 * w / 900, y + 854.6667 * h / 2270))
        acad.model.AddLine(APoint(x + 519.9339 * w / 900, y + 854.6667 * h / 2270),
                           APoint(x + 460.6308 * w / 900, y + 1077 * h / 2270))
        acad.model.AddLine(APoint(x + 460.6308 * w / 900, y + 1077 * h / 2270),
                           APoint(x + 178 * w / 900, y + 1077 * h / 2270))
        acad.model.AddLine(APoint(x + 178 * w / 900, y + 1077 * h / 2270),
                           APoint(x + 178 * w / 900, y + 854.6667 * h / 2270))
        acad.model.AddLine(APoint(x + 178 * w / 900, y + 854.6667 * h / 2270),
                           APoint(x + 178 * w / 900, y + 1077 * h / 2270))
        ########### another
        p0 = acad.model.AddLine(APoint(x + 150 * w / 900, y + 1165 * h / 2270),
                                APoint(x + 470.067 * w / 900, y + 1165 * h / 2270))
        p1 = acad.model.AddLine(APoint(x + 470.067 * w / 900, y + 1165 * h / 2270),
                                APoint(x + 424.7 * w / 900, y + 1443.3333 * h / 2270))
        p2 = acad.model.AddLine(APoint(x + 424.7 * w / 900, y + 1443.3333 * h / 2270),
                                APoint(x + 150 * w / 900, y + 1443.3333 * h / 2270))
        p3 = acad.model.AddLine(APoint(x + 150 * w / 900, y + 1443.3333 * h / 2270),
                                APoint(x + 150 * w / 900, y + 1165 * h / 2270))
        ##### light #####

        p4 = acad.model.AddLine(APoint(x + 150 * w / 900, y + 1165 * h / 2270),
                                APoint(x + 155 * w / 900, y + 1170 * h / 2270))
        p5 = acad.model.AddLine(APoint(x + 155 * w / 900, y + 1170 * h / 2270),
                                APoint(x + 463.9397 * w / 900, y + 1170 * h / 2270))
        p6 = acad.model.AddLine(APoint(x + 463.9397 * w / 900, y + 1170 * h / 2270),
                                APoint(x + 420.271 * w / 900, y + 1438.3333 * h / 2270))
        p7 = acad.model.AddLine(APoint(x + 420.271 * w / 900, y + 1438.3333 * h / 2270),
                                APoint(x + 155 * w / 900, y + 1438.3333 * h / 2270))
        ##### light #####

        p8 = acad.model.AddLine(APoint(x + 155 * w / 900, y + 1438.3333 * h / 2270),
                                APoint(x + 155 * w / 900, y + 1170 * h / 2270))
        p9 = acad.model.AddLine(APoint(x + 155 * w / 900, y + 1170 * h / 2270),
                                APoint(x + 170 * w / 900, y + 1185 * h / 2270))
        p10 = acad.model.AddLine(APoint(x + 170 * w / 900, y + 1185 * h / 2270),
                                 APoint(x + 445.6246 * w / 900, y + 1185 * h / 2270))
        p11 = acad.model.AddLine(APoint(x + 445.6246 * w / 900, y + 1185 * h / 2270),
                                 APoint(x + 407.0185 * w / 900, y + 1423.3333 * h / 2270))
        ##### light #####

        p12 = acad.model.AddLine(APoint(x + 407.0185 * w / 900, y + 1423.3333 * h / 2270),
                                 APoint(x + 170 * w / 900, y + 1423.3333 * h / 2270))
        p13 = acad.model.AddLine(APoint(x + 170 * w / 900, y + 1423.3333 * h / 2270),
                                 APoint(x + 170 * w / 900, y + 1185 * h / 2270))
        p14 = acad.model.AddLine(APoint(x + 170 * w / 900, y + 1185 * h / 2270),
                                 APoint(x + 178 * w / 900, y + 1193 * h / 2270))
        p15 = acad.model.AddLine(APoint(x + 178 * w / 900, y + 1193 * h / 2270),
                                 APoint(x + 435.8971 * w / 900, y + 1193 * h / 2270))
        ##### light #####

        p16 = acad.model.AddLine(APoint(x + 435.8971 * w / 900, y + 1193 * h / 2270),
                                 APoint(x + 399.9716 * w / 900, y + 1415.3333 * h / 2270))
        p17 = acad.model.AddLine(APoint(x + 399.9716 * w / 900, y + 1415.3333 * h / 2270),
                                 APoint(x + 178 * w / 900, y + 1415.3333 * h / 2270))
        p18 = acad.model.AddLine(APoint(x + 178 * w / 900, y + 1415.3333 * h / 2270),
                                 APoint(x + 178 * w / 900, y + 1193 * h / 2270))
        p19 = acad.model.AddLine(APoint(x + 178 * w / 900, y + 1193 * h / 2270),
                                 APoint(x + 178 * w / 900, y + 1415.3333 * h / 2270))
        ##### light #####
        p19.delete()
        p14.delete()
        p9.delete()
        p4.delete()

        ############## spline

        a = 0
        b = 0
        ox = 750 / 900 * w + x
        oy = 488.3 / 2270 * h + y
        for n in range(12):
            l0 = acad.model.AddLine(APoint(ox - a, oy + 6 * b), APoint(ox - a, oy + 1631.6 / 2270 * h - b))
            l0 = acad.model.AddLine(APoint(ox - a, oy + 1631.6 / 2270 * h - b),
                                    APoint(460 / 900 * w + a, oy + 1631.6 / 2270 * h - b))
            l0 = acad.model.AddLine(APoint(460 / 900 * w + a, oy + 1631.6 / 2270 * h - b),
                                    APoint(460 / 900 * w + a, 1841.6 / 2270 * h))
            acad.model.AddSpline(
                aDouble(460 / 900 * w + a, 1841.6 / 2270 * h, 0, 534.5 / 900 * w + a, 1149.9 / 2270 * h, 0, ox - a,
                        oy + b * 6, 0), APoint(0, 0), APoint(0, 0))
            a += (12 / 290) * w * 0.5 * 0.5
            b += (57.5 / 1631.66) * h * 0.2 * 0.5

        ####### last

        acad.model.AddPolyLine(aDouble(x + 178 * w / 900, y + 1531.3333 * h / 2270,
                                       x + 178 * w / 900, y + 1753.6667 * h / 2270,
                                       x + 373.4316 * w / 900, y + 1753.6667 * h / 2270,
                                       x + 387.0896 * w / 900, y + 1531.3333 * h / 2270,
                                       x + 170 * w / 900, y + 1523.3333 * h / 2270,
                                       x + 170 * w / 900, y + 1761.6667 * h / 2270,
                                       x + 381.2113 * w / 900, y + 1761.6667 * h / 2270,
                                       x + 395.8877 * w / 900, y + 1523.3333 * h / 2270,
                                       x + 155 * w / 900, y + 1508.3333 * h / 2270,
                                       x + 155 * w / 900, y + 1776.6667 * h / 2270,
                                       x + 395.8461 * w / 900, y + 1776.6667 * h / 2270,
                                       x + 412.4453 * w / 900, y + 1508.3333 * h / 2270,
                                       x + 150 * w / 900, y + 1503.3333 * h / 2270,
                                       x + 150 * w / 900, y + 1781.6667 * h / 2270,
                                       x + 400.7382 * w / 900, y + 1781.6667 * h / 2270,
                                       x + 417.9824 * w / 900, y + 1503.3333 * h / 2270
                                       ))
        # arcs
        r = 3347.2163
        an = 203
        for i in range(24):
            rr = acad.model.AddArc(APoint(3824.3611, 1857.6806), r, 180 * math.pi / 180, an * math.pi / 180)

            r -= 6
            an -= 1

    # draw0(0,0,900,2270)

    def draw1(self,x, y, w, h):
        import array as np
        import math as pi
        from pyautocad import Autocad, APoint, aDouble, math

        acad = Autocad(create_if_not_exists=True)
        acad.prompt("Hello, Autocad from Python\n")
        print(acad.doc.Name)
        wire = acad.model.AddPolyLine(aDouble(x + 320 * w / 390, y + 87.5 * h / 580, 0,
                                              x + 330 * w / 390, y + 95 * h / 580, 0,
                                              x + 330 * w / 390, y + 125 * h / 580, 0,
                                              x + 320 * w / 390, y + 132.5 * h / 580, 0,
                                              x + 330 * w / 390, y + 140 * h / 580, 0,
                                              x + 330 * w / 390, y + 170 * h / 580, 0,
                                              x + 320 * w / 390, y + 177.5 * h / 580, 0,
                                              x + 330 * w / 390, y + 185 * h / 580, 0,
                                              x + 330 * w / 390, y + 215 * h / 580, 0,
                                              x + 320 * w / 390, y + 222.5 * h / 580, 0,
                                              x + 330 * w / 390, y + 230 * h / 580, 0,
                                              x + 330 * w / 390, y + 260 * h / 580, 0,
                                              x + 320 * w / 390, y + 267.5 * h / 580, 0,
                                              x + 330 * w / 390, y + 275 * h / 580, 0,

                                              x + 330 * w / 390, y + 305 * h / 580, 0,
                                              x + 320 * w / 390, y + 312.5 * h / 580, 0,
                                              x + 330 * w / 390, y + 320 * h / 580, 0,
                                              x + 330 * w / 390, y + 350 * h / 580, 0,
                                              x + 320 * w / 390, y + 357.5 * h / 580, 0,
                                              x + 330 * w / 390, y + 365 * h / 580, 0,
                                              x + 330 * w / 390, y + 395 * h / 580, 0,
                                              x + 320 * w / 390, y + 402.5 * h / 580, 0,
                                              x + 330 * w / 390, y + 410 * h / 580, 0,
                                              x + 330 * w / 390, y + 440 * h / 580, 0,
                                              x + 320 * w / 390, y + 447.5 * h / 580, 0,
                                              x + 330 * w / 390, y + 455 * h / 580, 0,
                                              x + 330 * w / 390, y + 485 * h / 580, 0,
                                              x + 320 * w / 390, y + 492.5 * h / 580, 0,
                                              ))
        mwire = wire.Mirror(APoint(x + 320 * w / 390, y + 87.5 * h / 580
                                   ), APoint(x + 320 * w / 390, y + 492.5 * h / 580
                                             ))
        mwire.Mirror(APoint(x + 195 * w / 390, y + 60 * h / 580
                            ), APoint(x + 195 * w / 390, y + 520 * h / 580
                                      ))
        wire.Mirror(APoint(x + 195 * w / 390, y + 60 * h / 580
                           ), APoint(x + 195 * w / 390, y + 520 * h / 580
                                     ))

        ############ base

        base = acad.model.AddPolyLine(aDouble(x + 70 * w / 390, y + 87.5 * h / 580, 0,
                                              x + 80 * w / 390, y + 80 * h / 580, 0,
                                              x + 80 * w / 390, y + 73.3333 * h / 580, 0,
                                              x + 82.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 90 * w / 390, y + 80 * h / 580, 0,
                                              x + 120 * w / 390, y + 80 * h / 580, 0,
                                              x + 127.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 135 * w / 390, y + 80 * h / 580, 0,
                                              x + 165 * w / 390, y + 80 * h / 580, 0,
                                              x + 172.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 180 * w / 390, y + 80 * h / 580, 0,
                                              x + 210 * w / 390, y + 80 * h / 580, 0,
                                              x + 217.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 225 * w / 390, y + 80 * h / 580, 0,
                                              x + 255 * w / 390, y + 80 * h / 580, 0,
                                              x + 262.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 270 * w / 390, y + 80 * h / 580, 0,
                                              x + 300 * w / 390, y + 80 * h / 580, 0,
                                              x + 307.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 310 * w / 390, y + 73.3333 * h / 580, 0,
                                              x + 310 * w / 390, y + 80 * h / 580, 0,
                                              x + 320 * w / 390, y + 87.5 * h / 580, 0,
                                              x + 330 * w / 390, y + 80 * h / 580, 0,
                                              x + 330 * w / 390, y + 60 * h / 580, 0,
                                              x + 310 * w / 390, y + 60 * h / 580, 0,
                                              x + 310 * w / 390, y + 66.6667 * h / 580, 0,
                                              x + 307.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 300 * w / 390, y + 60 * h / 580, 0,
                                              x + 270 * w / 390, y + 60 * h / 580, 0,
                                              x + 262.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 255 * w / 390, y + 60 * h / 580, 0,
                                              x + 225 * w / 390, y + 60 * h / 580, 0,
                                              x + 217.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 210 * w / 390, y + 60 * h / 580, 0,
                                              x + 180 * w / 390, y + 60 * h / 580, 0,
                                              x + 172.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 165 * w / 390, y + 60 * h / 580, 0,
                                              x + 135 * w / 390, y + 60 * h / 580, 0,
                                              x + 127.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 120 * w / 390, y + 60 * h / 580, 0,
                                              x + 90 * w / 390, y + 60 * h / 580, 0,
                                              x + 82.5 * w / 390, y + 70 * h / 580, 0,
                                              x + 80 * w / 390, y + 66.6667 * h / 580, 0,
                                              x + 80 * w / 390, y + 60 * h / 580, 0,
                                              x + 60 * w / 390, y + 60 * h / 580, 0,
                                              x + 60 * w / 390, y + 80 * h / 580, 0,
                                              x + 70 * w / 390, y + 87.5 * h / 580, 0,
                                              ))
        base.Mirror(APoint(x + 390 * w / 390, y + 290 * h / 580
                           ), APoint(x + 0 * w / 390, y + 290 * h / 580
                                     ))
        ################## structure

        s = acad.model.AddPolyLine(aDouble(x + 105 * w / 390, y + 105 * h / 580, 0,
                                           x + 285 * w / 390, y + 105 * h / 580, 0,
                                           x + 285 * w / 390, y + 475 * h / 580, 0,
                                           x + 105 * w / 390, y + 475 * h / 580, 0,
                                           x + 105 * w / 390, y + 105 * h / 580, 0,
                                           ))
        s1 = acad.model.AddPolyLine(aDouble(x + 110 * w / 390, y + 110 * h / 580, 0,
                                            x + 280 * w / 390, y + 110 * h / 580, 0,
                                            x + 280 * w / 390, y + 470 * h / 580, 0,
                                            x + 110 * w / 390, y + 470 * h / 580, 0,
                                            x + 110 * w / 390, y + 110 * h / 580, 0,
                                            ))
        ############## core
        core = acad.model.AddPolyLine(aDouble(x + 172 * w / 390, y + 135 * h / 580, 0,
                                              x + 179.5 * w / 390, y + 145 * h / 580, 0,
                                              x + 187 * w / 390, y + 135 * h / 580, 0,
                                              x + 203 * w / 390, y + 135 * h / 580, 0,
                                              x + 210.5 * w / 390, y + 145 * h / 580, 0,
                                              x + 218 * w / 390, y + 135 * h / 580, 0,
                                              x + 255 * w / 390, y + 135 * h / 580, 0,
                                              x + 255 * w / 390, y + 177 * h / 580, 0,
                                              x + 245 * w / 390, y + 184.5 * h / 580, 0,
                                              x + 255 * w / 390, y + 192 * h / 580, 0,
                                              x + 255 * w / 390, y + 220.6835 * h / 580, 0,
                                              x + 245 * w / 390, y + 228.1835 * h / 580, 0,
                                              x + 255 * w / 390, y + 235.6835 * h / 580, 0,
                                              x + 255 * w / 390, y + 263.1212 * h / 580, 0,
                                              x + 245 * w / 390, y + 270.6212 * h / 580, 0,
                                              x + 255 * w / 390, y + 278.1212 * h / 580, 0,
                                              x + 255 * w / 390, y + 304.0127 * h / 580, 0,
                                              x + 245 * w / 390, y + 311.5127 * h / 580, 0,
                                              x + 255 * w / 390, y + 319.0127 * h / 580, 0,
                                              x + 255 * w / 390, y + 346.5978 * h / 580, 0,
                                              x + 245 * w / 390, y + 354.0978 * h / 580, 0,
                                              x + 255 * w / 390, y + 361.5978 * h / 580, 0,
                                              x + 255 * w / 390, y + 388 * h / 580, 0,
                                              x + 245 * w / 390, y + 395.5 * h / 580, 0,
                                              x + 255 * w / 390, y + 403 * h / 580, 0,
                                              x + 255 * w / 390, y + 445 * h / 580, 0,
                                              x + 218 * w / 390, y + 445 * h / 580, 0,
                                              x + 210.5 * w / 390, y + 435 * h / 580, 0,
                                              x + 203 * w / 390, y + 445 * h / 580, 0,
                                              x + 187 * w / 390, y + 445 * h / 580, 0,

                                              x + 179.5 * w / 390, y + 435 * h / 580, 0,
                                              x + 172 * w / 390, y + 445 * h / 580, 0,
                                              x + 135 * w / 390, y + 445 * h / 580, 0,
                                              x + 135 * w / 390, y + 403 * h / 580, 0,
                                              x + 145 * w / 390, y + 395.5 * h / 580, 0,
                                              x + 135 * w / 390, y + 388 * h / 580, 0,
                                              x + 135 * w / 390, y + 361.5978 * h / 580, 0,
                                              x + 145 * w / 390, y + 354.0978 * h / 580, 0,
                                              x + 135 * w / 390, y + 346.5978 * h / 580, 0,
                                              x + 135 * w / 390, y + 319.0127 * h / 580, 0,
                                              x + 145 * w / 390, y + 311.5127 * h / 580, 0,
                                              x + 135 * w / 390, y + 304.0127 * h / 580, 0,
                                              x + 135 * w / 390, y + 278.1212 * h / 580, 0,
                                              x + 145 * w / 390, y + 270.6212 * h / 580, 0,
                                              x + 135 * w / 390, y + 263.1212 * h / 580, 0,
                                              x + 135 * w / 390, y + 235.6835 * h / 580, 0,
                                              x + 145 * w / 390, y + 228.1835 * h / 580, 0,
                                              x + 135 * w / 390, y + 220.6835 * h / 580, 0,
                                              x + 135 * w / 390, y + 192 * h / 580, 0,
                                              x + 145 * w / 390, y + 184.5 * h / 580, 0,
                                              x + 135 * w / 390, y + 177 * h / 580, 0,
                                              x + 135 * w / 390, y + 135 * h / 580, 0,
                                              x + 172 * w / 390, y + 135 * h / 580, 0,
                                              x + 187 * w / 390, y + 155 * h / 580, 0,
                                              x + 203 * w / 390, y + 155 * h / 580, 0,
                                              x + 210.5 * w / 390, y + 145 * h / 580, 0,
                                              x + 218 * w / 390, y + 155 * h / 580, 0,
                                              x + 235 * w / 390, y + 155 * h / 580, 0,
                                              x + 235 * w / 390, y + 177 * h / 580, 0,
                                              x + 245 * w / 390, y + 184.5 * h / 580, 0,
                                              x + 235 * w / 390, y + 192 * h / 580, 0,
                                              x + 235 * w / 390, y + 220.6835 * h / 580, 0,
                                              x + 245 * w / 390, y + 228.1835 * h / 580, 0,
                                              x + 235 * w / 390, y + 235.6835 * h / 580, 0,
                                              x + 235 * w / 390, y + 263.1212 * h / 580, 0,
                                              x + 245 * w / 390, y + 270.6212 * h / 580, 0,
                                              x + 235 * w / 390, y + 278.1212 * h / 580, 0,
                                              x + 235 * w / 390, y + 304.0127 * h / 580, 0,
                                              x + 245 * w / 390, y + 311.5127 * h / 580, 0,
                                              x + 235 * w / 390, y + 319.0127 * h / 580, 0,
                                              x + 235 * w / 390, y + 346.5978 * h / 580, 0,
                                              x + 245 * w / 390, y + 354.0978 * h / 580, 0,
                                              x + 235 * w / 390, y + 361.5978 * h / 580, 0,
                                              x + 235 * w / 390, y + 388 * h / 580, 0,
                                              x + 245 * w / 390, y + 395.5 * h / 580, 0,
                                              x + 235 * w / 390, y + 403 * h / 580, 0,
                                              x + 235 * w / 390, y + 425 * h / 580, 0,
                                              x + 218 * w / 390, y + 425 * h / 580, 0,
                                              x + 210.5 * w / 390, y + 435 * h / 580, 0,
                                              x + 203 * w / 390, y + 425 * h / 580, 0,
                                              x + 187 * w / 390, y + 425 * h / 580, 0,
                                              x + 179.5 * w / 390, y + 435 * h / 580, 0,
                                              x + 172 * w / 390, y + 425 * h / 580, 0,
                                              x + 155 * w / 390, y + 425 * h / 580, 0,
                                              x + 155 * w / 390, y + 403 * h / 580, 0,
                                              x + 145 * w / 390, y + 395.5 * h / 580, 0,
                                              x + 155 * w / 390, y + 388 * h / 580, 0,
                                              x + 155 * w / 390, y + 361.5978 * h / 580, 0,
                                              x + 145 * w / 390, y + 354.0978 * h / 580, 0,
                                              x + 155 * w / 390, y + 346.5978 * h / 580, 0,
                                              x + 155 * w / 390, y + 319.0127 * h / 580, 0,
                                              x + 145 * w / 390, y + 311.5127 * h / 580, 0,
                                              x + 155 * w / 390, y + 304.0127 * h / 580, 0,
                                              x + 155 * w / 390, y + 278.1212 * h / 580, 0,
                                              x + 145 * w / 390, y + 270.6212 * h / 580, 0,
                                              x + 155 * w / 390, y + 263.1212 * h / 580, 0,
                                              x + 155 * w / 390, y + 235.6835 * h / 580, 0,
                                              x + 145 * w / 390, y + 228.1835 * h / 580, 0,
                                              x + 155 * w / 390, y + 220.6835 * h / 580, 0,
                                              x + 155 * w / 390, y + 192 * h / 580, 0,
                                              x + 145 * w / 390, y + 184.5 * h / 580, 0,
                                              x + 155 * w / 390, y + 177 * h / 580, 0,
                                              x + 155 * w / 390, y + 155 * h / 580, 0,
                                              x + 172 * w / 390, y + 155 * h / 580, 0,
                                              x + 179.5 * w / 390, y + 145 * h / 580, 0,
                                              ))
        ####### main
        m = acad.model.AddPolyLine(aDouble(x + 0 * w / 390, y + 0 * h / 580, 0,
                                           x + 390 * w / 390, y + 0 * h / 580, 0,
                                           x + 390 * w / 390, y + 580 * h / 580, 0,
                                           x + 0 * w / 390, y + 580 * h / 580, 0,
                                           x + 0 * w / 390, y + 0 * h / 580, 0,

                                           ))

        ### bove

        bove = acad.model.AddPolyLine(aDouble(x + 0 * w / 390, y + 600.2347 * h / 580, 0,
                                              x + 390 * w / 390, y + 600.2347 * h / 580, 0,
                                              x + 390 * w / 390, y + 780.2347 * h / 580, 0,
                                              x + 0 * w / 390, y + 780.2347 * h / 580, 0,
                                              x + 0 * w / 390, y + 600.2347 * h / 580, 0,
                                              ))

        ######## finish

        f = acad.model.AddPolyLine(aDouble(x + 82.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           x + 90 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 120 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 127.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           x + 135 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 165 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 172.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           x + 180 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 210 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 217.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           x + 225 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 255 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 262.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           x + 270 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 300 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 307.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           x + 310 * w / 390, y + 636.9013 * h / 580, 0,
                                           x + 310 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 330 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 330 * w / 390, y + 660.2347 * h / 580, 0,
                                           x + 320 * w / 390, y + 667.7347 * h / 580, 0,
                                           x + 330 * w / 390, y + 675.2347 * h / 580, 0,
                                           x + 330 * w / 390, y + 705.2347 * h / 580, 0,
                                           x + 320 * w / 390, y + 712.7347 * h / 580, 0,
                                           x + 330 * w / 390, y + 720.2347 * h / 580, 0,
                                           x + 330 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 310 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 310 * w / 390, y + 743.568 * h / 580, 0,
                                           x + 307.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 300 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 270 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 262.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 255 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 225 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 217.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 210 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 180 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 172.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 165 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 135 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 127.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 120 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 90 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 82.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 80 * w / 390, y + 743.568 * h / 580, 0,
                                           x + 80 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 60 * w / 390, y + 750.2347 * h / 580, 0,
                                           x + 60 * w / 390, y + 720.2347 * h / 580, 0,
                                           x + 70 * w / 390, y + 712.7347 * h / 580, 0,
                                           x + 60 * w / 390, y + 705.2347 * h / 580, 0,
                                           x + 60 * w / 390, y + 675.2347 * h / 580, 0,
                                           x + 70 * w / 390, y + 667.7347 * h / 580, 0,
                                           x + 60 * w / 390, y + 660.2347 * h / 580, 0,
                                           x + 60 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 80 * w / 390, y + 630.2347 * h / 580, 0,
                                           x + 80 * w / 390, y + 636.9013 * h / 580, 0,
                                           x + 90 * w / 390, y + 650.2347 * h / 580, 0,
                                           x + 120 * w / 390, y + 650.2347 * h / 580, 0,
                                           x + 127.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           x + 135 * w / 390, y + 650.2347 * h / 580, 0,
                                           x + 165 * w / 390, y + 650.2347 * h / 580, 0,
                                           x + 172.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           x + 180 * w / 390, y + 650.2347 * h / 580, 0,
                                           x + 210 * w / 390, y + 650.2347 * h / 580, 0,
                                           x + 217.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           x + 225 * w / 390, y + 650.2347 * h / 580, 0,
                                           x + 255 * w / 390, y + 650.2347 * h / 580, 0,
                                           x + 262.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           x + 270 * w / 390, y + 650.2347 * h / 580, 0,
                                           x + 300 * w / 390, y + 650.2347 * h / 580, 0,
                                           x + 307.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           x + 310 * w / 390, y + 643.568 * h / 580, 0,
                                           x + 310 * w / 390, y + 660.2347 * h / 580, 0,
                                           x + 320 * w / 390, y + 667.7347 * h / 580, 0,
                                           x + 310 * w / 390, y + 675.2347 * h / 580, 0,
                                           x + 310 * w / 390, y + 705.2347 * h / 580, 0,
                                           x + 320 * w / 390, y + 712.7347 * h / 580, 0,
                                           x + 310 * w / 390, y + 720.2347 * h / 580, 0,
                                           x + 310 * w / 390, y + 736.9013 * h / 580, 0,
                                           x + 307.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 300 * w / 390, y + 730.2347 * h / 580, 0,
                                           x + 270 * w / 390, y + 730.2347 * h / 580, 0,
                                           x + 262.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 255 * w / 390, y + 730.2347 * h / 580, 0,
                                           x + 225 * w / 390, y + 730.2347 * h / 580, 0,
                                           x + 217.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 210 * w / 390, y + 730.2347 * h / 580, 0,
                                           x + 180 * w / 390, y + 730.2347 * h / 580, 0,
                                           x + 172.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 165 * w / 390, y + 730.2347 * h / 580, 0,
                                           x + 135 * w / 390, y + 730.2347 * h / 580, 0,
                                           x + 127.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 120 * w / 390, y + 730.2347 * h / 580, 0,
                                           x + 90 * w / 390, y + 730.2347 * h / 580, 0,
                                           x + 82.5 * w / 390, y + 740.2347 * h / 580, 0,
                                           x + 80 * w / 390, y + 736.9013 * h / 580, 0,
                                           x + 80 * w / 390, y + 720.2347 * h / 580, 0,
                                           x + 70 * w / 390, y + 712.7347 * h / 580, 0,
                                           x + 80 * w / 390, y + 705.2347 * h / 580, 0,
                                           x + 80 * w / 390, y + 675.2347 * h / 580, 0,
                                           x + 70 * w / 390, y + 667.7347 * h / 580, 0,
                                           x + 80 * w / 390, y + 660.2347 * h / 580, 0,
                                           x + 80 * w / 390, y + 643.568 * h / 580, 0,
                                           x + 82.5 * w / 390, y + 640.2347 * h / 580, 0,
                                           ))



#q=shapes().draw1(0,0,900,2270)
